const templates = {
    "react":{
        framework:'React',
        i18n:false,
        unocss:false
    },
    "react-i18n":{
        framework:'React',
        i18n:true,
        unocss:false
    },
    "react-i18n-unocss":{
        framework:'React',
        i18n:true,
        unocss:true
    },
    "react-unocss":{
        framework:'React',
        i18n:false,
        unocss:true
    },
    "vue":{
        framework:'Vue',
        i18n:false,
        unocss:false
    },
    "vue-i18n":{
        framework:'Vue',
        i18n:true,
        unocss:false
    },
    "vue-i18n-unocss":{
        framework:'Vue',
        i18n:true,
        unocss:true
    },
    "vue-unocss":{
        framework:'Vue',
        i18n:false,
        unocss:true
    },
}

export default templates